-- CITY_DIM
ALTER TABLE ITI.CITY_DIM
 DROP PRIMARY KEY CASCADE;

DROP TABLE ITI.CITY_DIM CASCADE CONSTRAINTS;

CREATE TABLE ITI.CITY_DIM
(
  CITYID    NUMBER,
  CITYNAME  NVARCHAR2(100)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ITI.CITY_DIM_PK ON ITI.CITY_DIM
(CITYID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ITI.CITY_DIM ADD (
  CONSTRAINT CITY_DIM_PK
 PRIMARY KEY
 (CITYID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));




-- COUNTRY_DIM
ALTER TABLE ITI.COUNTRY_DIM
 DROP PRIMARY KEY CASCADE;

DROP TABLE ITI.COUNTRY_DIM CASCADE CONSTRAINTS;

CREATE TABLE ITI.COUNTRY_DIM
(
  COUNTRY_ID                NUMBER,
  COUNTRY_NUMERIC_3_CODE    NVARCHAR2(200),
  COUNTRY_ALPHA_2_CODE      NVARCHAR2(200),
  COUNTRY_ALPHA_3_CODE      NVARCHAR2(200),
  COUNTRY_NAME              NVARCHAR2(200),
  COUNTRY_SHORT_NAME        NVARCHAR2(200),
  COUNTRY_LONG_NAME         NVARCHAR2(200),
  CONTINENTAL_SECTION       NVARCHAR2(200),
  CONTINENTAL_SECTION_NAME  NVARCHAR2(200),
  CONTINENTS_ID             NUMBER,
  CONTINENTS_NAME           NVARCHAR2(204)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ITI.COUNTRY_DIM_PK ON ITI.COUNTRY_DIM
(COUNTRY_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ITI.COUNTRY_DIM ADD (
  CONSTRAINT COUNTRY_DIM_PK
 PRIMARY KEY
 (COUNTRY_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));





-- TAXITEMS_DIM
ALTER TABLE ITI.TAXITEMS_DIM
 DROP PRIMARY KEY CASCADE;

DROP TABLE ITI.TAXITEMS_DIM CASCADE CONSTRAINTS;

CREATE TABLE ITI.TAXITEMS_DIM
(
  ID             NUMBER,
  TAXDESC        NVARCHAR2(50),
  TAXPERCENTAGE  NUMBER,
  LICENSETYPE    NVARCHAR2(100)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ITI.TAXITMES_DIM_PK ON ITI.TAXITEMS_DIM
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ITI.TAXITEMS_DIM ADD (
  CONSTRAINT TAXITMES_DIM_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));




-- LICENSE_DIM
ALTER TABLE ITI.LICENSE_DIM
 DROP PRIMARY KEY CASCADE;

DROP TABLE ITI.LICENSE_DIM CASCADE CONSTRAINTS;

CREATE TABLE ITI.LICENSE_DIM
(
  LICENSENUMBER         NUMBER,
  TRADENAME             NVARCHAR2(250),
  TRADEADDRESS          NVARCHAR2(250),
  TRADETEL              NVARCHAR2(250),
  TRADEFAX              NVARCHAR2(250),
  TRADEOWNER            NVARCHAR2(200),
  TRADENOTES            NVARCHAR2(250),
  ISSUEDATE             DATE,
  CANCELATIONDATE       DATE,
  EXPIRYDATE            DATE,
  REPRESENTATIVENAME    NVARCHAR2(200),
  REPRESENTATIVEMOBILE  NVARCHAR2(200),
  MANAGERNAME           NVARCHAR2(200),
  EMAIL                 NVARCHAR2(200),
  LICENSETYPE           NVARCHAR2(200),
  AUDITORNAME           NVARCHAR2(200),
  AUDITORADDRESS        NVARCHAR2(200),
  FINANCEMANAGERNAME    NVARCHAR2(200),
  FINANCEMANAGEREMAIL   NVARCHAR2(200),
  FINANCEMANAGERPHONE   NVARCHAR2(200),
  FINANCEMANAGERMOBILE  NVARCHAR2(200),
  LICENSESATUS          NVARCHAR2(100),
  RATING                NVARCHAR2(200),
  TOTALROOMS            NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ITI.LICENSE_DIM_PK ON ITI.LICENSE_DIM
(LICENSENUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ITI.LICENSE_DIM ADD (
  CONSTRAINT LICENSE_DIM_PK
 PRIMARY KEY
 (LICENSENUMBER)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));




-- REVENUE_APPS_FACT
DROP TABLE ITI.REVENUE_APPS_FACT CASCADE CONSTRAINTS;

CREATE TABLE ITI.REVENUE_APPS_FACT
(
  LICENSENUMBER  NUMBER,
  TAXID          NUMBER,
  CITYID         NUMBER,
  DATEKEY        NUMBER,
  AMOUNT         NUMBER,
  EXPENSES       NUMBER,
  PROFIT         NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;




-- MONTHLY_RESIDENCEDATA_FACT
DROP TABLE ITI.MONTHLY_RESIDENCEDATA_FACT CASCADE CONSTRAINTS;

CREATE TABLE ITI.MONTHLY_RESIDENCEDATA_FACT
(
  LICENSENUMBER  NUMBER,
  CITYID         NUMBER,
  DATEKEY        NUMBER,
  NATIONALITYID  NUMBER,
  RESIDENCEID    NUMBER,
  ACTUAL_GUESTS  NUMBER,
  ROOM_NIGHTS    NUMBER,
  GUEST_NIGHTS   NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;





-- DAILY_OCCUPANCY_DATA_FACT
DROP TABLE ITI.DAILY_OCCUPANCY_DATA_FACT CASCADE CONSTRAINTS;

CREATE TABLE ITI.DAILY_OCCUPANCY_DATA_FACT
(
  LICENSENUMBER                 NUMBER,
  CITYID                        NUMBER,
  DATEKEY                       NUMBER,
  ROOMSAVAILABLE                NUMBER,
  ROOMS_OCCUPIED                NUMBER,
  ROOMS_OCCUPIED_WO_HOUSE       NUMBER,
  ROOMS_OCCUPIED_WO_COMPLIMENT  NUMBER,
  TOTAL_ROOMS                   NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


